CREATE TABLE USER (
    ID int AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) ,
    SURNAME VARCHAR(255)
);

CREATE TABLE LIBRARY(
    LIBRARY_ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    USER_ID INT FOREIGN KEY REFERENCES USER(ID),
    LIBRARY_NAME VARCHAR(255) NOT NULL

);

CREATE TABLE ITEMS(
    ITEM_ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    LIBRARY_ID INT FOREIGN KEY REFERENCES LIBRARY(ID),
    ITEM_NAME VARCHAR (255) NOT NULL,
    ITEM_AUTHOR VARCHAR (255),
    ITEM_TYPE VARCHAR(255)
);

