CREATE TABLE USERS (
    ID int AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) ,
    LASTNAME VARCHAR(255)
);

CREATE TABLE LIBRARY(
    LIBRARY_ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FK_USER_ID INT  NOT NULL,
    LIBRARY_NAME VARCHAR(255) NOT NULL

);

CREATE TABLE ITEMS(
    ITEM_ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FK_LIBRARY_ID INT NOT NULL,
    ITEM_NAME VARCHAR (255) NOT NULL,
    ITEM_AUTHOR VARCHAR (255),
    ITEM_TYPE VARCHAR(255)
);

